const {
    REACT_APP_FIREBASE_API_KEY,
    REACT_APP_FIREBASE_AUTH_DOMAIN,
    REACT_APP_FIREBASE_DATABASE_URL,
    REACT_APP_FIREBASE_PROJECT_ID,
    REACT_APP_FIREBASE_STORAGE_BUCKET,
    REACT_APP_FIREBASE_MESSAGING_SENDING_ID,
    REACT_APP_FIREBASE_APP_ID,
    REACT_APP_PUBLIC_VAPID_KEY
} = process.env;

const firebaseConfig = {
    apiKey: REACT_APP_FIREBASE_API_KEY,
    authDomain: REACT_APP_FIREBASE_AUTH_DOMAIN,
    databaseURL: REACT_APP_FIREBASE_DATABASE_URL,
    projectId: REACT_APP_FIREBASE_PROJECT_ID,
    storageBucket: REACT_APP_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: REACT_APP_FIREBASE_MESSAGING_SENDING_ID,
    appId: REACT_APP_FIREBASE_APP_ID,
};

export const config = {
    publicVapidKey: REACT_APP_PUBLIC_VAPID_KEY
}

export const token = 'fSwEgyVEkAQYsy5qv3kO4M:APA91bEhYmE32x5OIMUv6Z57Q9a8hitXPp82h4rUsF3dwkpTUss13IgmzcFTye0FxjwaVAOSaiz9q65C83wEFZRCleVWF5i-0z0sUaQ-WO2P9kEhkzLoApMXbNDcIIuH3LDsLWohkk1Y'

export default firebaseConfig;
